# Changes here will be overwritten by Copier
_commit: f435c63
_src_path: git@github.com:python-project-templates/base.git
add_extension: python
email: 3105306+timkpaine@users.noreply.github.com
github: airflow-laminar
project_description: Pydantic models of Airflow data structures
project_name: airflow-pydantic
python_version_primary: '3.11'
team: the airflow-pydantic authors
