name: Build Status

on:
  push:
    branches:
      - main
    tags:
      - v*
    paths-ignore:
      - LICENSE
      - README.md
  pull_request:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.11"]
        airflow: ["2", "3", ""]
        laminar: ["laminar", "no-laminar"]
        ccflow: ["ccflow", "no-ccflow"]
        exclude:
          # Skip laminar checks when no airflow
          - airflow: ""
            laminar: "laminar"
          # Skip laminar checks with ccflow
          - laminar: "laminar"
            ccflow: "ccflow"

    steps:
    - uses: actions/checkout@v5

    - uses: actions-ext/python/setup@main
      with:
        version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: make develop

    - name: Install Laminar dependencies
      run: uv pip install -e .[laminar]
      if: ${{ matrix.laminar == 'laminar' }}

    - name: Install Airflow 2.x
      run: uv pip install -e .[airflow]
      if: ${{ matrix.laminar == 'no-laminar' && matrix.airflow == '2' }}

    - name: Install Airflow 3.x
      run: uv pip install -e .[airflow3]
      if: ${{ matrix.laminar == 'no-laminar' && matrix.airflow == '3' }}

    - name: Lint
      run: make lint

    - name: Checks
      run: make checks

    - name: Build
      run: make build

    - name: Test
      run: make test
      if: ${{ matrix.laminar == 'no-laminar' }}

    - name: Test (ccflow)
      run: AIRFLOW_PYDANTIC_ENABLE_CCFLOW=1 make test
      if: ${{ matrix.ccflow == 'ccflow' }}

    - name: Test (coverage)
      run: make coverage
      if: ${{ matrix.laminar == 'laminar' }}

    - name: Upload test results (Python)
      uses: actions/upload-artifact@v5
      with:
        name: test-results-${{ matrix.os }}-${{ matrix.python-version }}
        path: junit.xml
      if: ${{ matrix.airflow == '2' && matrix.laminar == 'laminar' }}

    - name: Publish Unit Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      with:
        files: '**/junit.xml'
      if: ${{ matrix.airflow == '2' && matrix.laminar == 'laminar' }}

    - name: Upload coverage
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
      if: ${{ matrix.airflow == '2' && matrix.laminar == 'laminar' }}

    - name: Make dist
      run: make dist
      if: ${{ matrix.airflow == '2' && matrix.laminar == 'laminar' }}

    - uses: actions/upload-artifact@v5
      with:
        name: dist-${{matrix.os}}
        path: dist
      if: ${{ matrix.airflow == '2' && matrix.laminar == 'laminar' }}
